### ISSUE TITLE
using the pretain model infer images

### ISSUE THREAD

**Issue by PredyDaddy** [SiyuanHuang95/ManipVQA#2]
Hello, 
  Can I just use a 3090 to infer a images using the model in this website. https://huggingface.co/SiyuanH/ManipVQA/tree/main

  I have huge interesting in this project. But I don't have two A100, I dont think of to finetune this repo, I just want to infer a images. 

more specific, when I using this script, eval_manip.py,where can I find the tokenizer models, 

I used the script  eval_manip.py infer 
```python
python eval_manip.py --llama_type llama_qformerv2 --llama_config ./config.json --tokenizer_path ./tokenizer.model --img_root ./data/nocaps/images --image_path ./data/nocaps/images/cup.jpg --pretrained_path /home/dm/cqy/EmbodiedAI/ManipVQA_weights --device cuda --batch_size 1 --num_workers 1
```
the config.json and tokenizer.model from llama2, but it shows that 
```bash
  File "/home/dm/cqy/EmbodiedAI/ManipVQA-main/accessory/model/meta.py", line 45, in __init__
    llama_args: ModelArgs = ModelArgs(**llama_args)
TypeError: __init__() got an unexpected keyword argument 'model_type'
```
Many many thanks,

**Comment by SiyuanHuang95** [comment]
Hi, @PredyDaddy  thanks for your interests!

Actually, you may try the quant method to reduce the need for the GPU memory, check the lines from the original accessory [HERE](https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/3777c43940ddfb45d3bc1046b118ca4401747ee2/accessory/main_finetune.py#L172). Since we are following the most common setting with the original LLaMA-accessory repo, that should be easy achieved.

model_type? I did now where it comes...? I did not have this parameter in my code, If I remember clearly.

I am currently busy with my CoRL submission, so sorry for the late response!

If possible, I am planning to release another 7B model and quantization version after 7B.

BTW, may I know your needs for this model? Since, in our CoRL version, this has been extended to the 3D spaces, think that could be more suitable for you?

**Comment by PredyDaddy** [comment]
Thanks for reply! I hope I'm not interrupting your work for CoRL. I'm looking forward to the new release of your model.
