### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by RussRobin** [SiyuanHuang95/ManipVQA#4]
Hi , great thanks for this wonderful work.

I wonder if you plan to release the train and test set used in your work: images and QA files. Also, what's the relationship between handal_process.py and handal_grounding_tasks.py?

Millions of thanks!

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your interest in our project!

1. The dataset issue: Yes, we will release all the dataset stuff, maybe in 1-2 weeks. Since I am busy with another DDL now, no time to clean the dataset currently. I will let you know when the dataset is uploaded to HF.

2. grounding_tasks is the generation result from ChatGPT, where we add some language description to the original annotation.

**Comment by RussRobin** [comment]
Lots of thanks. Really looking forward to it!

**Comment by SiyuanHuang95** [comment]
Hi, I double check the dataset script provided in this repo, thought it would be enough for the VQA dataset generation. When any problem rasies, just let me know.

We also open-sourced another project recently, check it when you need the ability on 3D articulated object: https://github.com/changhaonan/A3VLM/tree/main/model

**Comment by RussRobin** [comment]
Thanks! Will you open-source the whole VQA dataset, or only dataset generation prompts are provided?

**Comment by SiyuanHuang95** [comment]
The prompts used in the both projects are only for the grounding tasks, and the mount is limited.

For the other stuff, you can use the script we provide to create locally
